filter:
    excluded_paths:
        - tests/*
        - examples/*

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=src/'
                coverage:
                    file: 'src/'
                    format: 'php-clover'