language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
 - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer self-update && composer update && phpunit
